name: Publish
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      # Build
      - name: Build project
        run: dotnet build src/StockportGovUK.AspNetCore.Attributes.TokenAuthentication.csproj
        
      # Pack
      - name: Package project
        run: dotnet pack src/StockportGovUK.AspNetCore.Attributes.TokenAuthentication.csproj --configuration Release

      # Publish
      - name: Publish project
        run: dotnet nuget push src/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.org
